export const GET_SERIES_DATA_LIST = 'GET_SERIES_DATA_LIST';
export const SET_SERIES_DATA_LIST = 'SET_SERIES_DATA_LIST';
export const SET_SERIES_DATA_LIST_LOADING = 'SET_SERIES_DATA_LIST_LOADING';
export const SET_SERIES_DATA_LIST_ERROR = 'SET_SERIES_DATA_LIST_ERROR';
export const GET_SELECTED_SERIES_DATA = 'GET_SELECTED_SERIES_DATA';
export const SET_SELECTED_SERIES_DATA = 'SET_SELECTED_SERIES_DATA';
export const SET_SELECTED_SERIES_DATA_LOADING = 'SET_SELECTED_SERIES_DATA_LOADING';
export const SET_SELECTED_SERIES_DATA_ERROR = 'SET_SELECTED_SERIES_DATA_ERROR';


